create sequence categories_sequence start 1 increment 1;
create sequence category_specifications_sequence start 1 increment 1;
create sequence hibernate_sequence start 1 increment 1;
create sequence item_images_sequence start 1 increment 1;
create sequence item_instance_specifications_sequence start 1 increment 1;
create sequence item_instances_sequence start 1 increment 1;
create sequence item_specifications_sequence start 1 increment 1;
create sequence items_sequence start 1 increment 1;
create sequence orders_sequence start 1 increment 1;
create sequence quantity_items_sequence start 1 increment 1;
create sequence users_sequence start 1 increment 1;
create table categories (id int8 not null, image varchar(255), name varchar(255), parent_id int8, primary key (id));
create table category_specifications (id int8 not null, choices varchar(255), name varchar(255), category_id int8, primary key (id));
create table item_images (id int8 not null, image varchar(255) not null, item_instance_id int8, primary key (id));
create table item_instance_specifications (id int8 not null, value varchar(255), category_specification_id int8 not null, item_id int8 not null, primary key (id));
create table item_instances (id int8 not null, stock int4, item_id int8 not null, primary key (id));
create table item_specifications (id int8 not null, value varchar(255), category_specification_id int8, item_id int8, primary key (id));
create table items (id int8 not null, description TEXT, name varchar(255), price float8 check (price>=1), category_id int8 not null, primary key (id));
create table orders (id int8 not null, created_at timestamp, status varchar(255), user_id int8 not null, primary key (id));
create table quantity_items (id int8 not null, quantity int4 check (quantity>=1), item_id int8, order_id int8, primary key (id));
create table refresh_tokens (id int8 not null, expiry_date timestamp not null, token varchar(255) not null, user_id int8, primary key (id));
create table roles (id int8 not null, name varchar(20), primary key (id));
create table user_roles (user_id int8 not null, role_id int8 not null, primary key (user_id, role_id));
create table users (id int8 not null, email varchar(60), name varchar(100), password varchar(120), primary key (id));
alter table if exists refresh_tokens add constraint UK_ghpmfn23vmxfu3spu3lfg4r2d unique (token);
alter table if exists users add constraint UK6dotkott2kjsp8vw4d0m25fb7 unique (email);
alter table if exists categories add constraint FKsaok720gsu4u2wrgbk10b5n8d foreign key (parent_id) references categories;
alter table if exists category_specifications add constraint FK3l95j7k25l461bi255dqoo0ic foreign key (category_id) references categories;
alter table if exists item_images add constraint FKcbvxi9rdj729yect4eq4jvpkh foreign key (item_instance_id) references item_instances;
alter table if exists item_instance_specifications add constraint FKcna6dgrp9fqivt89vqhtntdhd foreign key (category_specification_id) references category_specifications;
alter table if exists item_instance_specifications add constraint FKrf69srbq3qn6rpm401tabbqge foreign key (item_id) references item_instances;
alter table if exists item_instances add constraint FK8ogxarjx43tebg9fohshjkle9 foreign key (item_id) references items;
alter table if exists item_specifications add constraint FKa46huvikcwmocoilknw5loivp foreign key (category_specification_id) references category_specifications;
alter table if exists item_specifications add constraint FKrbqtfd2tloofu9k7g7fm527il foreign key (item_id) references items;
alter table if exists items add constraint FKjcdcde7htb3tyjgouo4g9xbmr foreign key (category_id) references categories;
alter table if exists orders add constraint FK32ql8ubntj5uh44ph9659tiih foreign key (user_id) references users;
alter table if exists quantity_items add constraint FK1lgtk72yvsq9br6wjymecfunx foreign key (item_id) references item_instances;
alter table if exists quantity_items add constraint FKaa94qs9qfs0tlveo35lgbv573 foreign key (order_id) references orders;
alter table if exists refresh_tokens add constraint FK1lih5y2npsf8u5o3vhdb9y0os foreign key (user_id) references users;
alter table if exists user_roles add constraint FKh8ciramu9cc9q3qcqiv4ue8a6 foreign key (role_id) references roles;
alter table if exists user_roles add constraint FKhfh9dx7w3ubf1co1vdev94g3f foreign key (user_id) references users;
