spring:
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: create

  datasource:
    url: jdbc:postgresql://localhost:5432/bikeShop
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

settings:
  image:
    path: /media/

  jwt:
    secret: bikeshop_jwt
    expiration: 6000000
    refresh-expiration: 864000000