spring:
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:postgresql://database:5432/bikeShop
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

settings:
  mode: production
  image:
    path: /usr/src/app/media/

  jwt:
    secret: bikeshop_jwt
    expiration: 6000000
    refresh-expiration: 864000000

springdoc:
  swagger-ui:
    operationsSorter: method